### PR TITLE
Use existing msg object instead of using new_msg

### PR DESCRIPTION
**Pull request by Dennis14e**
The msg is currently being completely overridden, resulting in the loss of previous information.
This pull request fixes this "bug".

### CODE REVIEW

**Comment by mattdavis90** [comment]
Hi Dennis, thanks for your pull request. I'm slightly nervous about merging this as I believe that the behaviour of all of the nodes that I've used that interact with external services, like this one does, overwrite the message. I'm more than happy to be proven wrong though.

**Comment by Dennis14e** [comment]
Hi,
All nodes I have used so far have continued to use the old msg, for example [node-red-contrib-fritz](https://github.com/bashGroup/node-red-contrib-fritz/blob/master/fritz.js).

**Comment by mattdavis90** [comment]
Ah, I understand now. Sorry, I thought you were referring to overwriting msg.payload. You are correct I shouldn't be overwriting everything. Maybe the best solution is to not create the new_msg object at all and just manipulate msg. I'm happy to make these edits, or accept a PR

**Comment by Dennis14e** [comment]
@mattdavis90 Hi, I updated this PR. Can you take a look at it?

**Comment by mattdavis90** [comment]
Sorry it has taken a couple of days to look at this. I'll do the merge now, update the version number and push it up to npm. Should be in nodered shortly.

**Pull request merged**
